arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
description: Home Assistant Control Objects
init: false
map:
  - config:rw
name: haco
options: { }
panel_icon: mdi:network-pos
schema: { }
services:
  - mqtt:need
slug: haco
url: https://link.frontmatter.ai/haco
version: 0.0.2
