arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
description: Home Assistant Control Objects
init: false
map:
  - config:rw
name: haco
options:
  assignments:
    - config: null
      identifier: null
panel_icon: mdi:network-pos
schema:
  assignments:
    - config: str
      identifier: str
services:
  - mqtt:need
slug: haco
url: https://fmtr.link/haco
version: 0.0.23
